### ISSUE TITLE
GPIO 0 Bug

### ISSUE THREAD

**Issue by NedalLive** [manoukianv/TMC2208Pilot#1]
Tout d'abord merci bcp pour ce fabuleux travail ! 
Je me suis aperçu que GPIO 0  cause un bug de boot du NodeMCU
LED allumé en bleu continue. il suffi de débrancher le câble du Gpio 0 pour que le NodeMCU boot correstement. 
-------------------------------------------------------------------------------------------------------------
First of all thank you bcp for this fabulous job!
I realized that GPIO 0 causes a NodeMCU boot bug
LED lit in solid blue. it was enough to unplug the cable of Gpio 0 for the NodeMCU boot correstly.

**Comment by manoukianv** [comment]
Fixed with delay startup

**Comment by didkivskyy** [comment]
Hi.
Does this bug relate to a warning written over the pinout photo in the Wiki?
If so can I ignore it if I'll have startup delay?

Thanks!
