### ISSUE TITLE
TMC 1 Random Bug

### ISSUE THREAD

**Issue by NedalLive** [manoukianv/TMC2208Pilot#17]
Je rencontre un Bug du TMC1 de maniere aleatoire.
Reamr + RAMPS 1.6
aleatoirement mon Moteur X (TMC1) ne fonctionne plus.
Solution le debrancher et reboot de la machine.
par la suite c'est mon moteur E (TMC4) qui ne fonctionne plus...
Cela peux ce produire à l'allumage comme pendant un print.

Solution actuel seullement laisser le TMC4 branché (utilisation du SpreadCycle) 

------------------------------------------
I encounter a TMC1 Bug in a random way.
Reamr + RAMPS 1.6
randomly my X Engine (TMC1) no longer works.
Solution unplug and reboot the machine.
later it's my E (TMC4) engine that does not work anymore ...
This can happen on ignition as during a print.

Current solution only to leave the TMC4 plugged in (using the SpreadCycle)

**Comment by manoukianv** [comment]
fix in #18
