### ISSUE TITLE
Delay Boot NodeMCU

### ISSUE THREAD

**Issue by NedalLive** [manoukianv/TMC2208Pilot#2]
Est-il possible de temporiser le boot du NodeMCU de 5sec ?
Ceci afin qu'il ne démarre pas avant les Drivers cela peux causer des defauts de lecture aleatoire. 
--------------------------------------------------------
is it possible to delay the boot of NodeMCU 5sec?
This so that it does not boot before the Drivers, can cause a random read fault...

**Comment by manoukianv** [comment]
Good idea

**Comment by manoukianv** [comment]
The time to wait will be set in the conf.h file

**Comment by NedalLive** [comment]
Thanks !
