### ISSUE TITLE
Refresh Button

### ISSUE THREAD

**Issue by NedalLive** [manoukianv/TMC2208Pilot#3]
Est-il possible d'ajouter un bouton ''Refresh'' sur la page web.
cela permettrait de renvoyer les valeur au drivers même après une erreur de boot du NodeMCU 
-----------------------------------------
Is it possible to add a ''Refresh'' button on the web page.
this would return the value to the drivers even after a NodeMCU boot error

**Comment by manoukianv** [comment]
What do you think about "Reapply settings now !"

**Comment by NedalLive** [comment]
for the button text ? 
that seems alright to me !
